export * from './Registration/Registration';
export * from './Login/Login';
export * from './TermsOfUse/TermsOfUse';
export { default as PrivacyPolicy } from './PrivacyPolicy/PrivacyPolicy';
export { default as Friends } from './Friends/Friends';
export { default as Welcome } from './Welcome/Welcome';
export { default as AccessGeo } from './AccessGeo/AccessGeo';
export { default as AccessGeoError } from './AccessGeoError/AccessGeoError';
export { default as Profile } from './Profile/Profile';
export { default as AccessAge } from './AccessAge/AccessAge';
export { default as ComingSoon } from './ComingSoon/ComingSoon';
