export * from './Registration/Registration.jsx';
export * from './Login/Login.jsx';
export { default as TermsOfUse } from './TermsOfUse/TermsOfUse.tsx';
export { default as PrivacyPolicy } from './PrivacyPolicy/PrivacyPolicy.tsx';
export * from './Friends/Friends.jsx';
export * from './Welcome/Welcome';
export * from './AccessGeo/AccessGeo.jsx';
export * from './AccessGeoError/AccessGeoError.jsx';
export * from './Profile/Profile.jsx';
export * from './AccessAge/AccessAge';
export * from './ComingSoon/ComingSoon.jsx';
