name: frontend workflow

on:
  push:
    branches-ignore:
      - "main"
      - "develop"
  pull_request:
    branches:
      - "main"
      - "develop"
    types:
      - closed

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Commit
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.15.0
      - name: Create yarn directory
        run: |
          if [ ! -d "$HOME/.yarn" ]; then
            mkdir "$HOME/.yarn"
          fi
      - name: Cache yarn dependencies
        id: cache-yarn
        uses: actions/cache@v2
        env:
          cache-name: cache-yarn
        with:
          path: ~/.yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-yarn-${{ env.cache-name }}-
            ${{ runner.os }}-yarn-
            ${{ runner.os }}-
      - name: Install Dependencies
        # if: ${{ steps.cache-yarn.outputs.cache-hit != 'true' }}
        run: |
          yarn install --non-interactive
      - name: Run Prettier
        run: |
          yarn format
      - name: Run Lint
        run: |
          yarn lint

  build_and_push_to_docker_hub:
    name: Push image to DockerHub
    runs-on: ubuntu-latest
    needs: tests
    # if: github.event.pull_request.merged == true && github.base_ref == 'main'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up docker buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD  }}

      - name: Push to DockerHub
        uses: docker/build-push-action@v2
        with:
          context: "{{defaultContext}}"
          push: True
          tags: ${{ secrets.DOCKER_USERNAME }}/friends-locator-frontend:latest
          file: ./Dockerfile
